# Generated by Django 4.2.2 on 2023-07-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('short_desc', models.TextField(max_length=500)),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='img')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
    ]
