# Generated by Django 4.2.2 on 2023-07-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0003_alter_recipes_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='short_desc',
            field=models.TextField(max_length=50),
        ),
    ]
