# Generated by Django 4.2.2 on 2023-07-06 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0009_alter_recipes_short_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('text_comments', models.TextField(max_length=2000, verbose_name='Текст комментаря')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_app.recipes', verbose_name='Post')),
            ],
        ),
    ]
