# Generated by Django 4.2.3 on 2023-07-13 17:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0016_alter_recipes_text_fifth_alter_recipes_text_fourth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Recipe'),
        ),
    ]
