# Generated by Django 4.2.3 on 2023-07-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0017_alter_recipes_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='text_fifth',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='text_fourth',
        ),
    ]
