# Generated by Django 4.2.3 on 2023-07-14 12:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0019_alter_recipes_text_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='text_second',
            field=tinymce.models.HTMLField(),
        ),
    ]
