# Generated by Django 4.2.3 on 2023-07-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0021_alter_recipes_text_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Назва страв'),
        ),
    ]
