# Generated by Django 4.2.2 on 2023-07-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0007_recipes_food_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='text_fourth',
        ),
    ]
