# Generated by Django 4.2.2 on 2023-07-10 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0012_alter_comments_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
