# Generated by Django 4.2.2 on 2023-07-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0013_comments_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='email',
        ),
    ]
