# Generated by Django 4.2.3 on 2023-07-12 18:09

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0015_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
