# Generated by Django 4.2.3 on 2023-07-13 16:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0015_recipes_text_fifth_recipes_text_fourth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='text_fifth',
            field=ckeditor.fields.RichTextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='text_fourth',
            field=ckeditor.fields.RichTextField(verbose_name='text'),
        ),
    ]
