# Generated by Django 4.2.3 on 2023-07-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0020_alter_recipes_text_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='text_second',
            field=models.TextField(default='-', verbose_name='text'),
        ),
    ]
