# Generated by Django 4.2.3 on 2023-07-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0024_alter_comments_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='text_second',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='text_third',
        ),
    ]
